# Generated by Django 2.1.2 on 2018-10-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='me.jpg', upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
