# Generated by Django 2.1.3 on 2018-12-24 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0006_auto_20181115_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bids', to='trades.Bid')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='trades.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
