# Generated by Django 2.1.3 on 2018-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20181228_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='is invoiced'),
        ),
    ]
