# Generated by Django 2.1.3 on 2018-12-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='accepted time'),
        ),
        migrations.AddField(
            model_name='bid',
            name='agreed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='agreed time'),
        ),
        migrations.AddField(
            model_name='bid',
            name='invoiced_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invoiced time'),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_agreed',
            field=models.BooleanField(default=False, verbose_name='is agreed'),
        ),
    ]
