# Generated by Django 2.1.3 on 2019-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_auto_20181229_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('ORIGIN', 'Origin'), ('SPOT', 'Spot')], default='SPOT', max_length=10, verbose_name='transport method'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('ORG', 'Organic'), ('CONV', 'Conventional')], default='ORG', max_length=10, verbose_name='product type'),
        ),
    ]
