# Generated by Django 2.1.2 on 2018-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181018_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rahman',
            field=models.BooleanField(default=False, help_text='Lower than admin and higher than regular user', verbose_name='rahman status'),
        ),
    ]
